#!/bin/bash

rm workingDirectory/*

#find /f/TEST/ -name first_run_crossline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name first_run_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name first_run_sideline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name first_run_thetas* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#
#find /f/TEST/ -name second_run_crossline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name second_run_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name second_run_sideline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name second_run_thetas* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#
#find /f/TEST/ -name third_run_crossline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name third_run_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name third_run_sideline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name third_run_thetas* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#
#find /f/TEST/ -name fourth_run_crossline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name fourth_run_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name fourth_run_sideline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name fourth_run_thetas* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#
#find /f/TEST/ -name fifth_run_crossline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name fifth_run_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name fifth_run_sideline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/
#find /f/TEST/ -name fifth_run_thetas* | sed -n '$p' | xargs -i cp -p {} workingDirectory/


find /f/TEST/ -name first_run_crossline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/first_run_crossline_distances.txt 
find /f/TEST/ -name first_run_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/first_run_distances.txt 
find /f/TEST/ -name first_run_sideline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/first_run_sideline_distances.txt 
find /f/TEST/ -name first_run_thetas* | sed -n '$p' | xargs -i cp -p {} workingDirectory/first_run_thetas.txt 

find /f/TEST/ -name second_run_crossline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/second_run_crossline_distances.txt 
find /f/TEST/ -name second_run_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/second_run_distances.txt 
find /f/TEST/ -name second_run_sideline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/second_run_sideline_distances.txt 
find /f/TEST/ -name second_run_thetas* | sed -n '$p' | xargs -i cp -p {} workingDirectory/second_run_thetas.txt 

find /f/TEST/ -name third_run_crossline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/third_run_crossline_distances.txt 
find /f/TEST/ -name third_run_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/third_run_distances.txt 
find /f/TEST/ -name third_run_sideline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/third_run_sideline_distances.txt 
find /f/TEST/ -name third_run_thetas* | sed -n '$p' | xargs -i cp -p {} workingDirectory/third_run_thetas.txt 

find /f/TEST/ -name fourth_run_crossline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/fourth_run_crossline_distances.txt 
find /f/TEST/ -name fourth_run_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/fourth_run_distances.txt 
find /f/TEST/ -name fourth_run_sideline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/fourth_run_sideline_distances.txt 
find /f/TEST/ -name fourth_run_thetas* | sed -n '$p' | xargs -i cp -p {} workingDirectory/fourth_run_thetas.txt 

find /f/TEST/ -name fifth_run_crossline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/fifth_run_crossline_distances.txt 
find /f/TEST/ -name fifth_run_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/fifth_run_distances.txt 
find /f/TEST/ -name fifth_run_sideline_distances* | sed -n '$p' | xargs -i cp -p {} workingDirectory/fifth_run_sideline_distances.txt 
find /f/TEST/ -name fifth_run_thetas* | sed -n '$p' | xargs -i cp -p {} workingDirectory/fifth_run_thetas.txt 
